### ISSUE TITLE
Scheduled micro-cut

### ISSUE THREAD

**Issue by bridgebrain** [pytti-tools/pytti-core#126] opened 2022-04-10 17:04 UTC
Would it be possible to create a sub-set of cut_pow that triggers x steps? I think it might be possible to get a high cohesion image (cut_pow 1), which every say 10 steps runs a deep detail step (3-5 cut_pow). This should result in extremely fine micro-details without losing bigger coherence

**Comment by bridgebrain** [comment] 2022-04-10 17:09
Alternatively, a system like ESR-GAN that tiles the image, then runs the same settings per tile. It could be cool to see that in action both constantly and as a per_x_steps to see what happens

**Comment by dmarx** [comment] 2022-04-10 17:22
off the top of my head, I think a way to implement this sort of scheduling could be to evaluate cut_pow the way weights are evaluated so you could make it a function of 't'. it's possible this is already supported but I'm not sure, will have to look into it. Regarding the image tiling: I've been thinking an approach like that might be a good way to facilitate high/arbitrary resolution generation.

**Comment by dmarx** [comment] 2022-06-11 00:08
calling this a duplicate of #79

**Closed by dmarx** 2022-06-11 00:08 UTC
Labels: duplicate, enhancement, config
