### ISSUE TITLE
Add audio input for induced motion

### ISSUE THREAD

**Issue by sbaier1** [pytti-tools/pytti-core#102] opened 2022-04-01 10:41 UTC
This is merely a ticket to notify you of my work in case you're working on something similar, i'm planning to create a PR in the near future once my [initial implementation](https://github.com/magnoton/pytti-core/tree/feat/fft-input) is somewhat ready (need to do some cleanup and perhaps some minor improvements as shown below, though it does work and produce usable results already).

I'd like to use pytti to make music visualizations / animations.

For that purpose i am in the process  of adding some [config parameters](https://github.com/magnoton/pytti-core/blob/feat/fft-input/src/pytti/config/structured_config.py#L78-L82):
- input audio file for reading arbitrary audio files
- FFT window size for configuring the analysis window
- offset parameter for testing or offsetting audio for other reasons
- some band parameters. i'm not 100% set on this yet, currently it splits the FFT frequencies into discrete bands with a hard cutoff, but i'm considering adding support for configuring arbitrary bandpass filters with configurable Q and frequency in the near future.

the amplitude of the bands in relation to the overall signal is then passed into the transforming math envs.

This allows for making animated music visualizations by reacting to the audio spectrum.
It could also be considered to add beat detection later on, but for now this is a relatively simple approach to the problem.

**Comment by dmarx** [comment] 2022-04-21 00:43
merged into test branch with PR #140 . Still to do:
* [ ] demonstration of this feature for documentation
* [ ] minimal test case

**Closed by dmarx** 2022-04-21 00:43 UTC
Labels: enhancement

**Comment by dmarx** [comment] 2022-04-24 20:04
Documentation added: https://pytti-tools.github.io/pytti-book/Settings.html#audio-reactivity-controls

**Comment by sbaier1** [comment] 2022-04-27 19:38
thank you! just had some free time and would've built something but the docs look pretty neat already.

**Comment by dmarx** [comment] 2022-04-28 00:51
lit. Mind if I tweet that out?
also yeah, any kind of tutorials or guides you wanna contribute to the docs would be very welcome!

**Comment by dmarx** [comment] 2022-04-28 00:54
aw fuck... I think it might be off by a frame (which is totally on me if that's the case). try adding an empty frame or duplicating the first frame and re-rendering the video. if it synchs better, I'm pretty sure I know what the problem is.

**Comment by sbaier1** [comment] 2022-05-02 18:01
> Mind if I tweet that out?
go ahead 👍 

> I think it might be off by a frame

oops, yeah i messed up my ffmpeg commands, here:

https://user-images.githubusercontent.com/20339314/166300252-89dec080-de2e-442e-9af5-88bd66f12bd8.mp4

**Comment by dmarx** [comment] 2022-05-02 18:15
sweet, glad there wasn't more synch stuff in pytti for the moment :p
